// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package omciSchema

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema(in *jlexer.Lexer, out *Schema) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Me":
			easyjson6a6f4b81Decode(in, &out.Me)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema(out *jwriter.Writer, in Schema) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Me\":"
		out.RawString(prefix[1:])
		easyjson6a6f4b81Encode(out, in.Me)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Schema) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Schema) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Schema) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Schema) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema(l, v)
}
func easyjson6a6f4b81Decode(in *jlexer.Lexer, out *struct {
	ClassId  uint16   `json:"id"`
	Name     string   `json:"name"`
	Access   string   `json:"access"`
	Type     string   `json:"type"`
	Action   []string `json:"action"`
	Instance struct {
		Type  string `json:"type"`
		Value uint16 `json:"value"`
	} `json:"instance"`
	Attributes struct {
		Attribute []AttributeSchema `json:"attribute"`
		Mask      uint16
		SbcMask   uint16
	} `json:"attributes"`
	ActionMap ActionMapType
	Alarms    struct {
		Alarm []AlarmSchema `json:"alarm"`
	} `json:"alarms"`
	TestRequestAttributes struct {
		TestRequestAttribute []AttributeSchema `json:"attribute"`
	} `json:"testRequestAttrs"`
	TestResultAttributes struct {
		TestResultAttribute []AttributeSchema `json:"attribute"`
	} `json:"testResultAttrs"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ClassId = uint16(in.Uint16())
		case "name":
			out.Name = string(in.String())
		case "access":
			out.Access = string(in.String())
		case "type":
			out.Type = string(in.String())
		case "action":
			if in.IsNull() {
				in.Skip()
				out.Action = nil
			} else {
				in.Delim('[')
				if out.Action == nil {
					if !in.IsDelim(']') {
						out.Action = make([]string, 0, 4)
					} else {
						out.Action = []string{}
					}
				} else {
					out.Action = (out.Action)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Action = append(out.Action, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "instance":
			easyjson6a6f4b81Decode1(in, &out.Instance)
		case "attributes":
			easyjson6a6f4b81Decode2(in, &out.Attributes)
		case "ActionMap":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.ActionMap = make(ActionMapType)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v2 string
					v2 = string(in.String())
					(out.ActionMap)[key] = v2
					in.WantComma()
				}
				in.Delim('}')
			}
		case "alarms":
			easyjson6a6f4b81Decode3(in, &out.Alarms)
		case "testRequestAttrs":
			easyjson6a6f4b81Decode4(in, &out.TestRequestAttributes)
		case "testResultAttrs":
			easyjson6a6f4b81Decode5(in, &out.TestResultAttributes)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a6f4b81Encode(out *jwriter.Writer, in struct {
	ClassId  uint16   `json:"id"`
	Name     string   `json:"name"`
	Access   string   `json:"access"`
	Type     string   `json:"type"`
	Action   []string `json:"action"`
	Instance struct {
		Type  string `json:"type"`
		Value uint16 `json:"value"`
	} `json:"instance"`
	Attributes struct {
		Attribute []AttributeSchema `json:"attribute"`
		Mask      uint16
		SbcMask   uint16
	} `json:"attributes"`
	ActionMap ActionMapType
	Alarms    struct {
		Alarm []AlarmSchema `json:"alarm"`
	} `json:"alarms"`
	TestRequestAttributes struct {
		TestRequestAttribute []AttributeSchema `json:"attribute"`
	} `json:"testRequestAttrs"`
	TestResultAttributes struct {
		TestResultAttribute []AttributeSchema `json:"attribute"`
	} `json:"testResultAttrs"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Uint16(uint16(in.ClassId))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"access\":"
		out.RawString(prefix)
		out.String(string(in.Access))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"action\":"
		out.RawString(prefix)
		if in.Action == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.Action {
				if v3 > 0 {
					out.RawByte(',')
				}
				out.String(string(v4))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"instance\":"
		out.RawString(prefix)
		easyjson6a6f4b81Encode1(out, in.Instance)
	}
	{
		const prefix string = ",\"attributes\":"
		out.RawString(prefix)
		easyjson6a6f4b81Encode2(out, in.Attributes)
	}
	{
		const prefix string = ",\"ActionMap\":"
		out.RawString(prefix)
		if in.ActionMap == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v5First := true
			for v5Name, v5Value := range in.ActionMap {
				if v5First {
					v5First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v5Name))
				out.RawByte(':')
				out.String(string(v5Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"alarms\":"
		out.RawString(prefix)
		easyjson6a6f4b81Encode3(out, in.Alarms)
	}
	{
		const prefix string = ",\"testRequestAttrs\":"
		out.RawString(prefix)
		easyjson6a6f4b81Encode4(out, in.TestRequestAttributes)
	}
	{
		const prefix string = ",\"testResultAttrs\":"
		out.RawString(prefix)
		easyjson6a6f4b81Encode5(out, in.TestResultAttributes)
	}
	out.RawByte('}')
}
func easyjson6a6f4b81Decode5(in *jlexer.Lexer, out *struct {
	TestResultAttribute []AttributeSchema `json:"attribute"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "attribute":
			if in.IsNull() {
				in.Skip()
				out.TestResultAttribute = nil
			} else {
				in.Delim('[')
				if out.TestResultAttribute == nil {
					if !in.IsDelim(']') {
						out.TestResultAttribute = make([]AttributeSchema, 0, 0)
					} else {
						out.TestResultAttribute = []AttributeSchema{}
					}
				} else {
					out.TestResultAttribute = (out.TestResultAttribute)[:0]
				}
				for !in.IsDelim(']') {
					var v6 AttributeSchema
					(v6).UnmarshalEasyJSON(in)
					out.TestResultAttribute = append(out.TestResultAttribute, v6)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a6f4b81Encode5(out *jwriter.Writer, in struct {
	TestResultAttribute []AttributeSchema `json:"attribute"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"attribute\":"
		out.RawString(prefix[1:])
		if in.TestResultAttribute == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.TestResultAttribute {
				if v7 > 0 {
					out.RawByte(',')
				}
				(v8).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
func easyjson6a6f4b81Decode4(in *jlexer.Lexer, out *struct {
	TestRequestAttribute []AttributeSchema `json:"attribute"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "attribute":
			if in.IsNull() {
				in.Skip()
				out.TestRequestAttribute = nil
			} else {
				in.Delim('[')
				if out.TestRequestAttribute == nil {
					if !in.IsDelim(']') {
						out.TestRequestAttribute = make([]AttributeSchema, 0, 0)
					} else {
						out.TestRequestAttribute = []AttributeSchema{}
					}
				} else {
					out.TestRequestAttribute = (out.TestRequestAttribute)[:0]
				}
				for !in.IsDelim(']') {
					var v9 AttributeSchema
					(v9).UnmarshalEasyJSON(in)
					out.TestRequestAttribute = append(out.TestRequestAttribute, v9)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a6f4b81Encode4(out *jwriter.Writer, in struct {
	TestRequestAttribute []AttributeSchema `json:"attribute"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"attribute\":"
		out.RawString(prefix[1:])
		if in.TestRequestAttribute == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v10, v11 := range in.TestRequestAttribute {
				if v10 > 0 {
					out.RawByte(',')
				}
				(v11).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
func easyjson6a6f4b81Decode3(in *jlexer.Lexer, out *struct {
	Alarm []AlarmSchema `json:"alarm"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "alarm":
			if in.IsNull() {
				in.Skip()
				out.Alarm = nil
			} else {
				in.Delim('[')
				if out.Alarm == nil {
					if !in.IsDelim(']') {
						out.Alarm = make([]AlarmSchema, 0, 1)
					} else {
						out.Alarm = []AlarmSchema{}
					}
				} else {
					out.Alarm = (out.Alarm)[:0]
				}
				for !in.IsDelim(']') {
					var v12 AlarmSchema
					(v12).UnmarshalEasyJSON(in)
					out.Alarm = append(out.Alarm, v12)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a6f4b81Encode3(out *jwriter.Writer, in struct {
	Alarm []AlarmSchema `json:"alarm"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"alarm\":"
		out.RawString(prefix[1:])
		if in.Alarm == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v13, v14 := range in.Alarm {
				if v13 > 0 {
					out.RawByte(',')
				}
				(v14).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
func easyjson6a6f4b81Decode2(in *jlexer.Lexer, out *struct {
	Attribute []AttributeSchema `json:"attribute"`
	Mask      uint16
	SbcMask   uint16
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "attribute":
			if in.IsNull() {
				in.Skip()
				out.Attribute = nil
			} else {
				in.Delim('[')
				if out.Attribute == nil {
					if !in.IsDelim(']') {
						out.Attribute = make([]AttributeSchema, 0, 0)
					} else {
						out.Attribute = []AttributeSchema{}
					}
				} else {
					out.Attribute = (out.Attribute)[:0]
				}
				for !in.IsDelim(']') {
					var v15 AttributeSchema
					(v15).UnmarshalEasyJSON(in)
					out.Attribute = append(out.Attribute, v15)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "Mask":
			out.Mask = uint16(in.Uint16())
		case "SbcMask":
			out.SbcMask = uint16(in.Uint16())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a6f4b81Encode2(out *jwriter.Writer, in struct {
	Attribute []AttributeSchema `json:"attribute"`
	Mask      uint16
	SbcMask   uint16
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"attribute\":"
		out.RawString(prefix[1:])
		if in.Attribute == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v16, v17 := range in.Attribute {
				if v16 > 0 {
					out.RawByte(',')
				}
				(v17).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"Mask\":"
		out.RawString(prefix)
		out.Uint16(uint16(in.Mask))
	}
	{
		const prefix string = ",\"SbcMask\":"
		out.RawString(prefix)
		out.Uint16(uint16(in.SbcMask))
	}
	out.RawByte('}')
}
func easyjson6a6f4b81Decode1(in *jlexer.Lexer, out *struct {
	Type  string `json:"type"`
	Value uint16 `json:"value"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "type":
			out.Type = string(in.String())
		case "value":
			out.Value = uint16(in.Uint16())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a6f4b81Encode1(out *jwriter.Writer, in struct {
	Type  string `json:"type"`
	Value uint16 `json:"value"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.Uint16(uint16(in.Value))
	}
	out.RawByte('}')
}
func easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema1(in *jlexer.Lexer, out *OmciTrace) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "header":
			easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema2(in, &out.Header)
		case "contents":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Contents = make(map[string]interface{})
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v18 interface{}
					if m, ok := v18.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v18.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v18 = in.Interface()
					}
					(out.Contents)[key] = v18
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema1(out *jwriter.Writer, in OmciTrace) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"header\":"
		out.RawString(prefix[1:])
		easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema2(out, in.Header)
	}
	{
		const prefix string = ",\"contents\":"
		out.RawString(prefix)
		if in.Contents == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v19First := true
			for v19Name, v19Value := range in.Contents {
				if v19First {
					v19First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v19Name))
				out.RawByte(':')
				if m, ok := v19Value.(easyjson.Marshaler); ok {
					m.MarshalEasyJSON(out)
				} else if m, ok := v19Value.(json.Marshaler); ok {
					out.Raw(m.MarshalJSON())
				} else {
					out.Raw(json.Marshal(v19Value))
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OmciTrace) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OmciTrace) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OmciTrace) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OmciTrace) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema1(l, v)
}
func easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema2(in *jlexer.Lexer, out *EngineOmciHeader) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Tcid":
			out.Tcid = uint16(in.Uint16())
		case "AR":
			out.AR = uint8(in.Uint8())
		case "AK":
			out.AK = uint8(in.Uint8())
		case "MsgType":
			out.MsgType = uint8(in.Uint8())
		case "MsgTypeName":
			out.MsgTypeName = string(in.String())
		case "DevId":
			out.DevId = uint8(in.Uint8())
		case "MeClass":
			out.MeClass = uint16(in.Uint16())
		case "MeClassName":
			out.MeClassName = string(in.String())
		case "MeInst":
			out.MeInst = uint16(in.Uint16())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema2(out *jwriter.Writer, in EngineOmciHeader) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Tcid\":"
		out.RawString(prefix[1:])
		out.Uint16(uint16(in.Tcid))
	}
	{
		const prefix string = ",\"AR\":"
		out.RawString(prefix)
		out.Uint8(uint8(in.AR))
	}
	{
		const prefix string = ",\"AK\":"
		out.RawString(prefix)
		out.Uint8(uint8(in.AK))
	}
	{
		const prefix string = ",\"MsgType\":"
		out.RawString(prefix)
		out.Uint8(uint8(in.MsgType))
	}
	{
		const prefix string = ",\"MsgTypeName\":"
		out.RawString(prefix)
		out.String(string(in.MsgTypeName))
	}
	{
		const prefix string = ",\"DevId\":"
		out.RawString(prefix)
		out.Uint8(uint8(in.DevId))
	}
	{
		const prefix string = ",\"MeClass\":"
		out.RawString(prefix)
		out.Uint16(uint16(in.MeClass))
	}
	{
		const prefix string = ",\"MeClassName\":"
		out.RawString(prefix)
		out.String(string(in.MeClassName))
	}
	{
		const prefix string = ",\"MeInst\":"
		out.RawString(prefix)
		out.Uint16(uint16(in.MeInst))
	}
	out.RawByte('}')
}
func easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema3(in *jlexer.Lexer, out *OmciMsgTypeInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "message-type-info":
			easyjson6a6f4b81Decode6(in, &out.MsgTypeInfo)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema3(out *jwriter.Writer, in OmciMsgTypeInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"message-type-info\":"
		out.RawString(prefix[1:])
		easyjson6a6f4b81Encode6(out, in.MsgTypeInfo)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OmciMsgTypeInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OmciMsgTypeInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OmciMsgTypeInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OmciMsgTypeInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema3(l, v)
}
func easyjson6a6f4b81Decode6(in *jlexer.Lexer, out *struct {
	Timeout    uint16        `json:"timeout"`
	Debouncing uint16        `json:"debouncing"`
	Retries    uint16        `json:"retries"`
	DBTimeout  uint16        `json:"device-busy-timeout"`
	DBRetries  uint16        `json:"device-busy-retries"`
	MsgTypes   []OmciMsgType `json:"message-types"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "timeout":
			out.Timeout = uint16(in.Uint16())
		case "debouncing":
			out.Debouncing = uint16(in.Uint16())
		case "retries":
			out.Retries = uint16(in.Uint16())
		case "device-busy-timeout":
			out.DBTimeout = uint16(in.Uint16())
		case "device-busy-retries":
			out.DBRetries = uint16(in.Uint16())
		case "message-types":
			if in.IsNull() {
				in.Skip()
				out.MsgTypes = nil
			} else {
				in.Delim('[')
				if out.MsgTypes == nil {
					if !in.IsDelim(']') {
						out.MsgTypes = make([]OmciMsgType, 0, 1)
					} else {
						out.MsgTypes = []OmciMsgType{}
					}
				} else {
					out.MsgTypes = (out.MsgTypes)[:0]
				}
				for !in.IsDelim(']') {
					var v20 OmciMsgType
					(v20).UnmarshalEasyJSON(in)
					out.MsgTypes = append(out.MsgTypes, v20)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a6f4b81Encode6(out *jwriter.Writer, in struct {
	Timeout    uint16        `json:"timeout"`
	Debouncing uint16        `json:"debouncing"`
	Retries    uint16        `json:"retries"`
	DBTimeout  uint16        `json:"device-busy-timeout"`
	DBRetries  uint16        `json:"device-busy-retries"`
	MsgTypes   []OmciMsgType `json:"message-types"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"timeout\":"
		out.RawString(prefix[1:])
		out.Uint16(uint16(in.Timeout))
	}
	{
		const prefix string = ",\"debouncing\":"
		out.RawString(prefix)
		out.Uint16(uint16(in.Debouncing))
	}
	{
		const prefix string = ",\"retries\":"
		out.RawString(prefix)
		out.Uint16(uint16(in.Retries))
	}
	{
		const prefix string = ",\"device-busy-timeout\":"
		out.RawString(prefix)
		out.Uint16(uint16(in.DBTimeout))
	}
	{
		const prefix string = ",\"device-busy-retries\":"
		out.RawString(prefix)
		out.Uint16(uint16(in.DBRetries))
	}
	{
		const prefix string = ",\"message-types\":"
		out.RawString(prefix)
		if in.MsgTypes == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v21, v22 := range in.MsgTypes {
				if v21 > 0 {
					out.RawByte(',')
				}
				(v22).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
func easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema4(in *jlexer.Lexer, out *OmciMsgType) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "id":
			out.Id = uint8(in.Uint8())
		case "increment-mib-data-sync":
			out.IncrementMds = bool(in.Bool())
		case "timeout":
			if in.IsNull() {
				in.Skip()
				out.Timeout = nil
			} else {
				if out.Timeout == nil {
					out.Timeout = new(uint16)
				}
				*out.Timeout = uint16(in.Uint16())
			}
		case "debouncing":
			if in.IsNull() {
				in.Skip()
				out.Debouncing = nil
			} else {
				if out.Debouncing == nil {
					out.Debouncing = new(uint16)
				}
				*out.Debouncing = uint16(in.Uint16())
			}
		case "retries":
			if in.IsNull() {
				in.Skip()
				out.Retries = nil
			} else {
				if out.Retries == nil {
					out.Retries = new(uint16)
				}
				*out.Retries = uint16(in.Uint16())
			}
		case "device-busy-timeout":
			if in.IsNull() {
				in.Skip()
				out.DBTimeout = nil
			} else {
				if out.DBTimeout == nil {
					out.DBTimeout = new(uint16)
				}
				*out.DBTimeout = uint16(in.Uint16())
			}
		case "device-busy-retries":
			if in.IsNull() {
				in.Skip()
				out.DBRetries = nil
			} else {
				if out.DBRetries == nil {
					out.DBRetries = new(uint16)
				}
				*out.DBRetries = uint16(in.Uint16())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema4(out *jwriter.Writer, in OmciMsgType) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.Uint8(uint8(in.Id))
	}
	{
		const prefix string = ",\"increment-mib-data-sync\":"
		out.RawString(prefix)
		out.Bool(bool(in.IncrementMds))
	}
	if in.Timeout != nil {
		const prefix string = ",\"timeout\":"
		out.RawString(prefix)
		out.Uint16(uint16(*in.Timeout))
	}
	if in.Debouncing != nil {
		const prefix string = ",\"debouncing\":"
		out.RawString(prefix)
		out.Uint16(uint16(*in.Debouncing))
	}
	if in.Retries != nil {
		const prefix string = ",\"retries\":"
		out.RawString(prefix)
		out.Uint16(uint16(*in.Retries))
	}
	if in.DBTimeout != nil {
		const prefix string = ",\"device-busy-timeout\":"
		out.RawString(prefix)
		out.Uint16(uint16(*in.DBTimeout))
	}
	if in.DBRetries != nil {
		const prefix string = ",\"device-busy-retries\":"
		out.RawString(prefix)
		out.Uint16(uint16(*in.DBRetries))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OmciMsgType) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OmciMsgType) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OmciMsgType) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OmciMsgType) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema4(l, v)
}
func easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema5(in *jlexer.Lexer, out *AttributeStructureField) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "size":
			out.Size = uint16(in.Uint16())
		case "format":
			out.Format = string(in.String())
		case "expectedValue":
			out.ExpectedValue = uint16(in.Uint16())
		case "structure":
			(out.Table).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema5(out *jwriter.Writer, in AttributeStructureField) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"size\":"
		out.RawString(prefix)
		out.Uint16(uint16(in.Size))
	}
	{
		const prefix string = ",\"format\":"
		out.RawString(prefix)
		out.String(string(in.Format))
	}
	{
		const prefix string = ",\"expectedValue\":"
		out.RawString(prefix)
		out.Uint16(uint16(in.ExpectedValue))
	}
	{
		const prefix string = ",\"structure\":"
		out.RawString(prefix)
		(in.Table).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AttributeStructureField) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AttributeStructureField) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AttributeStructureField) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AttributeStructureField) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema5(l, v)
}
func easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema6(in *jlexer.Lexer, out *AttributeStructure) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "fields":
			if in.IsNull() {
				in.Skip()
				out.Fields = nil
			} else {
				in.Delim('[')
				if out.Fields == nil {
					if !in.IsDelim(']') {
						out.Fields = make([]AttributeStructureField, 0, 0)
					} else {
						out.Fields = []AttributeStructureField{}
					}
				} else {
					out.Fields = (out.Fields)[:0]
				}
				for !in.IsDelim(']') {
					var v23 AttributeStructureField
					(v23).UnmarshalEasyJSON(in)
					out.Fields = append(out.Fields, v23)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema6(out *jwriter.Writer, in AttributeStructure) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"fields\":"
		out.RawString(prefix[1:])
		if in.Fields == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v24, v25 := range in.Fields {
				if v24 > 0 {
					out.RawByte(',')
				}
				(v25).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AttributeStructure) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AttributeStructure) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AttributeStructure) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AttributeStructure) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema6(l, v)
}
func easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema7(in *jlexer.Lexer, out *AttributeSchema) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "position":
			out.Position = uint16(in.Uint16())
		case "size":
			out.Size = uint16(in.Uint16())
		case "format":
			out.Format = string(in.String())
		case "table":
			out.IsTable = bool(in.Bool())
		case "access":
			if in.IsNull() {
				in.Skip()
				out.Access = nil
			} else {
				in.Delim('[')
				if out.Access == nil {
					if !in.IsDelim(']') {
						out.Access = make([]string, 0, 4)
					} else {
						out.Access = []string{}
					}
				} else {
					out.Access = (out.Access)[:0]
				}
				for !in.IsDelim(']') {
					var v26 string
					v26 = string(in.String())
					out.Access = append(out.Access, v26)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "category":
			out.Category = string(in.String())
		case "structure":
			(out.Table).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema7(out *jwriter.Writer, in AttributeSchema) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"position\":"
		out.RawString(prefix)
		out.Uint16(uint16(in.Position))
	}
	{
		const prefix string = ",\"size\":"
		out.RawString(prefix)
		out.Uint16(uint16(in.Size))
	}
	{
		const prefix string = ",\"format\":"
		out.RawString(prefix)
		out.String(string(in.Format))
	}
	{
		const prefix string = ",\"table\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsTable))
	}
	{
		const prefix string = ",\"access\":"
		out.RawString(prefix)
		if in.Access == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v27, v28 := range in.Access {
				if v27 > 0 {
					out.RawByte(',')
				}
				out.String(string(v28))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix)
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"structure\":"
		out.RawString(prefix)
		(in.Table).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AttributeSchema) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AttributeSchema) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AttributeSchema) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AttributeSchema) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema7(l, v)
}
func easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema8(in *jlexer.Lexer, out *AlarmSchema) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "number":
			out.Number = uint8(in.Uint8())
		case "name":
			out.Name = string(in.String())
		case "description":
			out.Description = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema8(out *jwriter.Writer, in AlarmSchema) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"number\":"
		out.RawString(prefix[1:])
		out.Uint8(uint8(in.Number))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AlarmSchema) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AlarmSchema) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a6f4b81EncodeOmciAnalyzerSrcOmciSchema8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AlarmSchema) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AlarmSchema) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a6f4b81DecodeOmciAnalyzerSrcOmciSchema8(l, v)
}
